### ISSUE TITLE
blocksat-cli:  "ValueError: could not convert string to float: 'NA'"

### ISSUE THREAD

**Issue by BTCBellyButton** [Blockstream/satellite#79]
Running 
blocksat-cli sat-ip -a 192.168.1.41

After some time I get this error:

2021-09-05 18:51:54 WARNING  Failed to fetch the frontend status.ity = 0.0%;
Exception in thread Thread-1:alse; Level = -71.67dBm; Signal Quality = 0.0%;
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/satip.py", line 186, in _monitoring_thread
    status = sat_ip.fe_stats()
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/satip.py", line 146, in fe_stats
    return self._parse_fe_info(fe['frontend'])
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/satip.py", line 47, in _parse_fe_info
    signal_level = ((10 * float(fe_info['sq'])) - 3440) / 48
ValueError: could not convert string to float: 'NA'

**Comment by blockstreamsatellite** [comment]
Hi @BTCBellyButton ,

Thanks for reporting the error. We've released a new version (v0.4.0) of the Blocksat CLI today, which includes a fix for this problem. Please, upgrade the CLI by running:

```
sudo pip3 install blocksat-cli --upgrade
```

Or refer to the [upgrade instructions](https://blockstream.github.io/satellite/doc/quick-reference.html#cli-installation-and-upgrade).

Thanks
